[guides.advanced]
title = "Advanced"
description = """\
Go beyond the basics, become a Vector pro, and extract the full potential of Vector.\
"""

[guides.getting-started]
title = "Getting Started"
description = """\
Take Vector from zero to production in under 10 minutes.\
"""

[guides.setup]
title = "Setup"
description = """\
Targeted guides for setting up specific sources and sinks.\
"""
