[guides.advanced]
title = "Advanced"
description = """\
Going beyond the basics. Extract the full potential Vector has to offer.\
"""

[guides.getting-started]
title = "Getting Started"
description = """\
Take Vector from zero to production in under 10 minutes.\
"""

[guides.setup]
title = "Setup"
description = """\
Targeted guides for setting up specific sources and sinks.\
"""
